// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.mjs";
import * as React from "react";
import * as DataGtm from "../../../utils/DataGtm.mjs";
import * as DS_Button from "../element/DS_Button.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function DS_ButtonContainer$Floating1(Props) {
  var label = Props.label;
  var disabled = Props.disabled;
  var onClick = Props.onClick;
  var buttonType = Props.buttonType;
  var dataGtm = Props.dataGtm;
  var isFixedOpt = Props.isFixed;
  var isFixed = isFixedOpt !== undefined ? isFixedOpt : true;
  var tmp = {
    label: label
  };
  if (disabled !== undefined) {
    tmp.disabled = Caml_option.valFromOption(disabled);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  if (buttonType !== undefined) {
    tmp.buttonType = Caml_option.valFromOption(buttonType);
  }
  return React.createElement("div", {
              className: Cx.cx([
                    "fixed w-full max-w-3xl bottom-0 left-1/2 -translate-x-1/2 p-5 gradient-cta-t tab-highlight-color",
                    isFixed ? "fixed" : "absolute"
                  ])
            }, Belt_Option.mapWithDefault(dataGtm, React.createElement(DS_Button.Normal.Large1.make, tmp), (function (dataGtm$p) {
                    var tmp = {
                      label: label
                    };
                    if (disabled !== undefined) {
                      tmp.disabled = Caml_option.valFromOption(disabled);
                    }
                    if (onClick !== undefined) {
                      tmp.onClick = Caml_option.valFromOption(onClick);
                    }
                    if (buttonType !== undefined) {
                      tmp.buttonType = Caml_option.valFromOption(buttonType);
                    }
                    return React.createElement(DataGtm.make, {
                                children: React.createElement("div", {
                                      onClick: (function (param) {
                                          
                                        })
                                    }, React.createElement(DS_Button.Normal.Large1.make, tmp)),
                                dataGtm: dataGtm$p
                              });
                  })));
}

var Floating1 = {
  make: DS_ButtonContainer$Floating1
};

function DS_ButtonContainer$Full1(Props) {
  var label = Props.label;
  var disabled = Props.disabled;
  var onClick = Props.onClick;
  var buttonType = Props.buttonType;
  var dataGtm = Props.dataGtm;
  var tmp = {
    label: label
  };
  if (disabled !== undefined) {
    tmp.disabled = Caml_option.valFromOption(disabled);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  if (buttonType !== undefined) {
    tmp.buttonType = Caml_option.valFromOption(buttonType);
  }
  return React.createElement("div", {
              className: "fixed w-full max-w-3xl bottom-0 left-1/2 -translate-x-1/2 tab-highlight-color"
            }, Belt_Option.mapWithDefault(dataGtm, React.createElement(DS_Button.Normal.Full1.make, tmp), (function (dataGtm$p) {
                    var tmp = {
                      label: label
                    };
                    if (disabled !== undefined) {
                      tmp.disabled = Caml_option.valFromOption(disabled);
                    }
                    if (onClick !== undefined) {
                      tmp.onClick = Caml_option.valFromOption(onClick);
                    }
                    if (buttonType !== undefined) {
                      tmp.buttonType = Caml_option.valFromOption(buttonType);
                    }
                    return React.createElement(DataGtm.make, {
                                children: React.createElement("div", {
                                      onClick: (function (param) {
                                          
                                        })
                                    }, React.createElement(DS_Button.Normal.Full1.make, tmp)),
                                dataGtm: dataGtm$p
                              });
                  })));
}

var Full1 = {
  make: DS_ButtonContainer$Full1
};

export {
  Floating1 ,
  Full1 ,
}
/* react Not a pure module */
