// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.mjs";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function DS_TopNavigation$Detail$Root(Props) {
  var children = Props.children;
  var className = Props.className;
  var bgClassNameOpt = Props.bgClassName;
  var bgClassName = bgClassNameOpt !== undefined ? bgClassNameOpt : "bg-white";
  var defaultStyle = Cx.cx([
        "fixed top-0 left-1/2 w-full flex justify-between items-center max-w-3xl -translate-x-1/2 p-3",
        bgClassName
      ]);
  return React.createElement("div", {
              className: Belt_Option.mapWithDefault(className, defaultStyle, (function (className$p) {
                      return Cx.cx([
                                  defaultStyle,
                                  bgClassName,
                                  className$p
                                ]);
                    }))
            }, children);
}

var Root = {
  make: DS_TopNavigation$Detail$Root
};

function DS_TopNavigation$Detail$Left(Props) {
  var children = Props.children;
  var className = Props.className;
  var defaultStyle = "mr-2";
  return React.createElement("div", {
              className: Belt_Option.mapWithDefault(className, defaultStyle, (function (className$p) {
                      return Cx.cx([
                                  defaultStyle,
                                  className$p
                                ]);
                    }))
            }, children);
}

var Left = {
  make: DS_TopNavigation$Detail$Left
};

function DS_TopNavigation$Detail$Center(Props) {
  var children = Props.children;
  var className = Props.className;
  var defaultStyle = "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 tracking-tight font-bold truncate";
  return React.createElement("div", {
              className: Belt_Option.mapWithDefault(className, defaultStyle, (function (className$p) {
                      return Cx.cx([
                                  defaultStyle,
                                  className$p
                                ]);
                    }))
            }, children);
}

var Center = {
  make: DS_TopNavigation$Detail$Center
};

function DS_TopNavigation$Detail$Right(Props) {
  var children = Props.children;
  var className = Props.className;
  var defaultStyle = "ml-2";
  return React.createElement("div", {
              className: Belt_Option.mapWithDefault(className, defaultStyle, (function (className$p) {
                      return Cx.cx([
                                  defaultStyle,
                                  className$p
                                ]);
                    }))
            }, children);
}

var Right = {
  make: DS_TopNavigation$Detail$Right
};

var Detail = {
  Root: Root,
  Left: Left,
  Center: Center,
  Right: Right
};

export {
  Detail ,
}
/* react Not a pure module */
