// Generated by ReScript, PLEASE EDIT WITH CARE


var vercelEnv = process.env.NEXT_PUBLIC_VERCEL_ENV;

var apiUrl = process.env.NEXT_PUBLIC_API_URL;

var graphqlApiUrl = apiUrl + "/graphql";

var fmbGraphqlApiUrl = apiUrl + "/farmmorning-bridge/graphql";

var channelTalkKey = process.env.NEXT_PUBLIC_CHANNEL_TALK_KEY;

var afterPayApiUrl = process.env.NEXT_PUBLIC_AFTER_PAY_API_URL;

var customerServicePaths = {
  rfqContactManager: "/40022",
  rfqMeatProcess: "/40277"
};

var buyerUploadGuideUri = process.env.NEXT_PUBLIC_BUYER_UPLOAD_GUIDE_URI;

var buyerOrderExcelFormUri = process.env.NEXT_PUBLIC_BUYER_ORDER_EXCEL_FORM_URI;

var cancelFormUrl = process.env.NEXT_PUBLIC_CANCEL_FORM_URL;

var imwebPayUrl = process.env.NEXT_PUBLIC_IMWEB_PAY_URL;

var s3PublicUrl = process.env.NEXT_PUBLIC_S3_PUBLIC_URL;

var buyerSignupSurveyKey = process.env.NEXT_PUBLIC_BUYER_SIGNUP_SURVEY_KEY;

var logo150x50 = process.env.NEXT_PUBLIC_LOGO_150x50_URI;

var statusPageKey = process.env.NEXT_PUBLIC_STATUSPAGE_KEY;

var statusPagePageId = process.env.NEXT_PUBLIC_STATUSPAGE_PAGE_ID;

var brazeWebApiKey = process.env.NEXT_PUBLIC_BRAZE_WEB_API_KEY;

var toggleOrderButton = process.env.NEXT_PUBLIC_TOGGLE_ORDER_BUTTON;

var orderAdmins = process.env.NEXT_PUBLIC_ORDER_ADMINS;

var termsUrl = process.env.NEXT_PUBLIC_TERMS;

var privacyAgreeUrl = process.env.NEXT_PUBLIC_PRIVACY_AGREE;

var privacyPolicyUrl = process.env.NEXT_PUBLIC_PRIVACY_POLICY;

var privacyMarketing = process.env.NEXT_PUBLIC_PRIVACY_MARKETING;

var copyrightUrl = process.env.NEXT_PUBLIC_COPYRIGHT;

var restApiUrl = apiUrl;

var originProd = "https://app.sinsunhi.com";

var sweettrackerUrl = "https://info.sweettracker.co.kr/tracking/5";

var customerServiceUrl = "https://freshmarket.channel.io/support-bots";

var kakaotalkChannel = "https://pf.kakao.com/_JftIs";

var downloadChromeUrl = "https://www.google.com/intl/ko/chrome/";

var downloadEdgeUrl = "https://www.microsoft.com/ko-kr/edge";

var paperformEmbedUrl = "https://paperform.co/__embed.min.js";

export {
  vercelEnv ,
  apiUrl ,
  restApiUrl ,
  graphqlApiUrl ,
  fmbGraphqlApiUrl ,
  channelTalkKey ,
  afterPayApiUrl ,
  originProd ,
  sweettrackerUrl ,
  customerServiceUrl ,
  customerServicePaths ,
  kakaotalkChannel ,
  buyerUploadGuideUri ,
  buyerOrderExcelFormUri ,
  cancelFormUrl ,
  downloadChromeUrl ,
  downloadEdgeUrl ,
  imwebPayUrl ,
  s3PublicUrl ,
  paperformEmbedUrl ,
  buyerSignupSurveyKey ,
  logo150x50 ,
  statusPageKey ,
  statusPagePageId ,
  brazeWebApiKey ,
  toggleOrderButton ,
  orderAdmins ,
  termsUrl ,
  privacyAgreeUrl ,
  privacyPolicyUrl ,
  privacyMarketing ,
  copyrightUrl ,
}
/* vercelEnv Not a pure module */
