// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";
import * as Router from "next/router";

function AppLink_Header(Props) {
  var router = Router.useRouter();
  return React.createElement(Head, {
              children: null
            }, React.createElement("meta", {
                  content: "sinsunhi://com.greenlabs.sinsunhi" + router.asPath + "",
                  property: "al:ios:url"
                }), React.createElement("meta", {
                  content: "",
                  property: "al:ios:app_store_id"
                }), React.createElement("meta", {
                  content: "신선하이",
                  property: "al:ios:app_name"
                }), React.createElement("meta", {
                  content: "sinsunhi://com.greenlabs.sinsunhi" + router.asPath + "",
                  property: "al:android:url"
                }), React.createElement("meta", {
                  content: "신선하이",
                  property: "al:android:app_name"
                }), React.createElement("meta", {
                  content: "com.greenlabs.sinsunhi",
                  property: "al:android:package"
                }), React.createElement("meta", {
                  content: "https://www.sinsunhi.com" + router.asPath + "",
                  property: "al:web:url"
                }));
}

var make = AppLink_Header;

export {
  make ,
}
/* react Not a pure module */
