// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function EmptyProducts(Props) {
  return React.createElement("div", {
              className: "grid col-span-full justify-center items-center text-black-gl h-96"
            }, React.createElement("div", {
                  className: ""
                }, "단품이 없습니다."));
}

var make = EmptyProducts;

export {
  make ,
}
/* react Not a pure module */
