// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReForm from "@rescriptbr/reform/src/ReForm.mjs";

function get(values, field) {
  if (field) {
    return values.producerCodes;
  } else {
    return values.producerName;
  }
}

function set(values, field, value) {
  if (field) {
    return {
            producerName: values.producerName,
            producerCodes: value
          };
  } else {
    return {
            producerName: value,
            producerCodes: values.producerCodes
          };
  }
}

var FormFields = {
  get: get,
  set: set
};

var Form = ReForm.Make({
      set: set,
      get: get
    });

var initialState = {
  producerName: "",
  producerCodes: ""
};

export {
  FormFields ,
  Form ,
  initialState ,
  
}
/* Form Not a pure module */
