// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactUtil from "./ReactUtil.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as CustomHooks from "./CustomHooks.mjs";

function push(data) {
  var layer = window.dataLayer;
  if (layer == null) {
    console.error("window.dataLayer is not defined");
  } else {
    layer.push(data);
  }
}

function DataGtm(Props) {
  var children = Props.children;
  var dataGtm = Props.dataGtm;
  return React.createElement(ReactUtil.SpreadProps.make, {
              children: children,
              props: {
                "data-gtm": dataGtm
              }
            });
}

function mergeUserIdUnsafe(data) {
  var userIdOrNull = Belt_Option.mapWithDefault(CustomHooks.Auth.getUser(undefined), null, (function (user) {
          return user.id;
        }));
  return Object.assign(data, {
              user_id: userIdOrNull,
              crm_id: userIdOrNull
            });
}

var make = DataGtm;

export {
  push ,
  make ,
  mergeUserIdUnsafe ,
}
/* react Not a pure module */
