// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function stopSyntheticDefaultEvent(e) {
  e.preventDefault();
  e.stopPropagation();
  
}

function stopSyntheticEventWithTarget(e) {
  stopSyntheticDefaultEvent(e);
  return e.target;
}

function interceptingHandler(f, e) {
  stopSyntheticDefaultEvent(e);
  return Curry._1(f, e);
}

export {
  stopSyntheticDefaultEvent ,
  stopSyntheticEventWithTarget ,
  interceptingHandler ,
  
}
/* No side effect */
