// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Locale from "../../../utils/Locale.mjs";
import * as Skeleton from "../../../components/Skeleton.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as CustomHooks from "../../../utils/CustomHooks.mjs";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as Hooks from "react-relay/hooks";
import * as RescriptRelay_Internal from "rescript-relay/src/RescriptRelay_Internal.mjs";
import * as PDPPriceBuyerFragment_graphql from "../../../__generated__/PDPPriceBuyerFragment_graphql.mjs";

function use(fRef) {
  var data = Hooks.useFragment(PDPPriceBuyerFragment_graphql.node, fRef);
  return RescriptRelay_Internal.internal_useConvertedValue(PDPPriceBuyerFragment_graphql.Internal.convertFragment, data);
}

function useOpt(opt_fRef) {
  var fr = opt_fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(opt_fRef)) : undefined;
  var nullableFragmentData = Hooks.useFragment(PDPPriceBuyerFragment_graphql.node, fr !== undefined ? Js_null_undefined.fromOption(Caml_option.some(Caml_option.valFromOption(fr))) : null);
  var data = (nullableFragmentData == null) ? undefined : Caml_option.some(nullableFragmentData);
  return RescriptRelay_Internal.internal_useConvertedValue((function (rawFragment) {
                if (rawFragment !== undefined) {
                  return PDPPriceBuyerFragment_graphql.Internal.convertFragment(rawFragment);
                }
                
              }), data);
}

var Fragment_productStatus_decode = PDPPriceBuyerFragment_graphql.Utils.productStatus_decode;

var Fragment_productStatus_fromString = PDPPriceBuyerFragment_graphql.Utils.productStatus_fromString;

var Fragment = {
  productStatus_decode: Fragment_productStatus_decode,
  productStatus_fromString: Fragment_productStatus_fromString,
  Types: undefined,
  use: use,
  useOpt: useOpt
};

function PDP_Price_Buyer$PC(Props) {
  var query = Props.query;
  var user = Curry._1(CustomHooks.User.Buyer.use2, undefined);
  var match = use(query);
  var isSoldout = match.status === "SOLDOUT";
  var priceLabel = Belt_Option.mapWithDefault(match.price, "", (function (price$p) {
          return Locale.Float.show(undefined, price$p, 0);
        }));
  if (typeof user === "number") {
    if (user !== 0) {
      return React.createElement("h1", {
                  className: "mt-5 text-[28px] text-green-500 font-bold"
                }, "공급가 회원공개");
    } else {
      return React.createElement(Skeleton.Box.make, {});
    }
  }
  var textColor = isSoldout ? "text-gray-600" : "text-gray-800";
  return React.createElement("h1", {
              className: "mt-5 text-[32px] font-bold" + textColor
            }, priceLabel, React.createElement("span", {
                  className: "text-lg"
                }, "원"));
}

var PC = {
  make: PDP_Price_Buyer$PC
};

function PDP_Price_Buyer$MO(Props) {
  var query = Props.query;
  var user = Curry._1(CustomHooks.User.Buyer.use2, undefined);
  var match = use(query);
  var isSoldout = match.status === "SOLDOUT";
  var priceLabel = Belt_Option.mapWithDefault(match.price, "", (function (price$p) {
          return Locale.Float.show(undefined, price$p, 0);
        }));
  if (typeof user === "number") {
    if (user !== 0) {
      return React.createElement("h1", {
                  className: "text-xl text-green-500 font-bold"
                }, "공급가 회원공개");
    } else {
      return React.createElement(Skeleton.Box.make, {});
    }
  }
  var textColor = isSoldout ? "text-gray-600" : "text-gray-800";
  return React.createElement("h1", {
              className: "text-xl font-bold " + textColor
            }, priceLabel, React.createElement("span", {
                  className: "text-lg"
                }, "원"));
}

var MO = {
  make: PDP_Price_Buyer$MO
};

export {
  Fragment ,
  PC ,
  MO ,
  
}
/* react Not a pure module */
