// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Env from "../../../constants/Env.mjs";
import * as React from "react";
import * as RelayEnv from "../../../constants/RelayEnv.mjs";
import Head from "next/head";
import * as DeviceDetect from "../../../bindings/DeviceDetect.mjs";
import * as Footer_Buyer from "../../../components/Footer_Buyer.mjs";
import * as Header_Buyer from "../../../components/Header_Buyer.mjs";
import * as ServerSideHelper from "../../../utils/ServerSideHelper.mjs";
import * as RfqCreateRequestButton from "../../../components/RfqCreateRequestButton.mjs";
import RfqCardPng from "../../../assets/rfq/rfq-card-1.png";
import RfqCardPng$1 from "../../../assets/rfq/rfq-card-2.png";
import RfqCardPng$2 from "../../../assets/rfq/rfq-card-3.png";
import RfqBoxImgPng from "../../../assets/rfq/rfq-box-img.png";
import RfqCardM1Png from "../../../assets/rfq/rfq-card-m1.png";
import RfqCardM2Png from "../../../assets/rfq/rfq-card-m2.png";
import RfqCardM3Png from "../../../assets/rfq/rfq-card-m3.png";
import RfqIndexBgPng from "../../../assets/rfq/rfq-index-bg.png";
import RfqCardImg1Png from "../../../assets/rfq/rfq-card-img1.png";
import RfqCardImg2Png from "../../../assets/rfq/rfq-card-img2.png";
import RfqIndexBgMPng from "../../../assets/rfq/rfq-index-bg-m.png";
import RfqCardImgM1Png from "../../../assets/rfq/rfq-card-img-m1.png";
import RfqCardImgM2Png from "../../../assets/rfq/rfq-card-img-m2.png";

var rfqBgImg = RfqIndexBgPng;

var rfqCard1 = RfqCardPng;

var rfqCard2 = RfqCardPng$1;

var rfqCard3 = RfqCardPng$2;

var rfqBox = RfqBoxImgPng;

var rfqCardImg1 = RfqCardImg1Png;

var rfqCardImg2 = RfqCardImg2Png;

var rfqCardM1 = RfqCardM1Png;

var rfqCardM2 = RfqCardM2Png;

var rfqCardM3 = RfqCardM3Png;

var rfqCardImgM1 = RfqCardImgM1Png;

var rfqCardImgM2 = RfqCardImgM2Png;

var rfqBgImgM = RfqIndexBgMPng;

function Rfq_Buyer$PC(Props) {
  var buttonStyle = "mt-[30px] text-xl text-white tracking-tighter leading-6 px-8 py-5 bg-primary rounded-lg";
  return React.createElement(React.Fragment, undefined, React.createElement(Header_Buyer.PC.make, {}), React.createElement("div", {
                  className: "min-w-[1280px]"
                }, React.createElement("section", {
                      className: "relative w-full"
                    }, React.createElement("img", {
                          className: "absolute object-cover h-full w-full -z-10",
                          src: rfqBgImg.src
                        }), React.createElement("div", {
                          className: "py-[110px]"
                        }, React.createElement("h2", {
                              className: "text-center whitespace-pre-line text-white font-bold text-[44px] leading-[61.44px]"
                            }, "원하는 육류 가격만 알려주세요\n", React.createElement("span", {
                                  className: "text-[#05FF00]"
                                }, "원가 절감 100%"), " 보장합니다"), React.createElement("div", {
                              className: "flex justify-center"
                            }, React.createElement(RfqCreateRequestButton.make, {
                                  className: buttonStyle,
                                  position: "top"
                                })), React.createElement("div", {
                              className: "flex justify-center gap-5 mt-[70px]"
                            }, React.createElement("img", {
                                  className: "w-[333px]",
                                  src: rfqCard1.src
                                }), React.createElement("img", {
                                  className: "w-[333px]",
                                  src: rfqCard2.src
                                }), React.createElement("img", {
                                  className: "w-[333px]",
                                  src: rfqCard3.src
                                })))), React.createElement("section", {
                      className: "relative w-full"
                    }, React.createElement("div", {
                          className: "flex flex-col items-center py-[135px]"
                        }, React.createElement("div", {
                              className: "w-full max-w-screen-lg bg-[#F6F9F6] rounded-[40px] py-20"
                            }, React.createElement("div", {
                                  className: "px-[72px]"
                                }, React.createElement("div", {
                                      className: "text-5xl font-bold"
                                    }, "업계 ", React.createElement("span", {
                                          className: "text-primary"
                                        }, "최저가로"), " 공급"), React.createElement("div", {
                                      className: "mt-5 text-2xl leading-9 tracking-tighter whitespace-pre-line text-gray-700"
                                    }, "30곳 이상의 대형 공급업체의 견적을 비교하여\n기존 공급업체보다 더 저렴한 가격을 보장해드립니다.")), React.createElement("div", {
                                  className: "flex mt-12 justify-end"
                                }, React.createElement("img", {
                                      className: "max-w-[890px]",
                                      src: rfqCardImg1.src
                                    }))), React.createElement("div", {
                              className: "max-w-screen-lg w-full relative bg-[#F6F9F6] py-20 px-[72px] rounded-[40px] mt-5 mx-0"
                            }, React.createElement("div", {
                                  className: "block justify-center items-center flex-col"
                                }, React.createElement("div", {
                                      className: "text-5xl font-bold"
                                    }, "재거래 시에도 "), React.createElement("div", {
                                      className: "text-5xl font-bold text-primary"
                                    }, "매번 최저가로"), React.createElement("div", {
                                      className: "mt-5 whitespace-pre-line text-2xl leading-9 tracking-tighter text-gray-700"
                                    }, "매 발주마다 최저가 견적만 자동 발송되어\n꾸준한 원가 절감효과를 누릴 수 있습니다."), React.createElement("div", {
                                      className: "block absolute right-0 top-0"
                                    }, React.createElement("img", {
                                          className: "max-w-[475px]",
                                          src: rfqCardImg2.src
                                        })))))), React.createElement("section", {
                      className: "flex justify-center py-[130px]"
                    }, React.createElement("div", {
                          className: "flex justify-start gap-5 px-0"
                        }, React.createElement("img", {
                              className: "w-[510px]",
                              src: rfqBox.src
                            }), React.createElement("div", {
                              className: "flex justify-center flex-col pl-[70px] text-left"
                            }, React.createElement("div", {
                                  className: "text-5xl font-bold"
                                }, React.createElement("span", undefined, "한 박스도 "), React.createElement("span", {
                                      className: "text-primary"
                                    }, "무료배송")), React.createElement("div", {
                                  className: "text-2xl leading-9 tracking-tighter text-gray-700 mt-5 whitespace-pre-line"
                                }, "한 박스 이상 주문 시 매장 앞으로\n배송비 0원에 배송해드립니다.")))), React.createElement("section", {
                      className: "relative w-full bg-[#3F4C65] py-[110px]"
                    }, React.createElement("div", {
                          className: "flex justify-center items-center flex-col text-white font-bold leading-[62px] text-[44px]"
                        }, React.createElement("h2", {
                              className: "whitespace-pre-line"
                            }, "첫 거래 시 ", React.createElement("span", {
                                  className: "text-primary"
                                }, "10만원 추가할인!"), "\n 1분만에 견적을 요청해보세요"), React.createElement("h3", {
                              className: "text-2xl font-normal text-center leading-9 mt-5 whitespace-pre-line"
                            }, "영업일 기준 견적요청 후 2시간 내로 견적서가 도착!\n", React.createElement("span", {
                                  className: "text-gray-400"
                                }, "(단, 16시 이후 견적요청 건은 다음 날 오전에 견적서를 발송해드려요)"))), React.createElement("div", {
                          className: "flex justify-center mt-2.5"
                        }, React.createElement(RfqCreateRequestButton.make, {
                              className: buttonStyle,
                              position: "bottom"
                            })))), React.createElement(Footer_Buyer.PC.make, {}));
}

var PC = {
  make: Rfq_Buyer$PC
};

function Rfq_Buyer$MO(Props) {
  var buttonStyle = "mt-[30px] text-xl text-white tracking-tighter leading-6 px-8 py-5 bg-primary rounded-lg";
  return React.createElement(React.Fragment, undefined, React.createElement(Header_Buyer.Mobile.make, {}), React.createElement("div", {
                  className: "min-w-[360px]"
                }, React.createElement("section", {
                      className: "relative"
                    }, React.createElement("img", {
                          className: "absolute object-cover h-full w-full -z-10",
                          src: rfqBgImgM.src
                        }), React.createElement("div", {
                          className: "py-20"
                        }, React.createElement("h2", {
                              className: "text-center text-[26px] leading-8 text-white font-bold whitespace-pre-line"
                            }, "원하는 육류 가격만 알려주세요\n", React.createElement("span", {
                                  className: "text-[#05FF00]"
                                }, "원가 절감 100%"), " 보장합니다"), React.createElement("div", {
                              className: "flex justify-center"
                            }, React.createElement(RfqCreateRequestButton.make, {
                                  className: buttonStyle,
                                  position: "top"
                                })), React.createElement("div", {
                              className: "flex flex-col items-center mt-10 gap-4"
                            }, React.createElement("img", {
                                  className: "w-[280px]",
                                  src: rfqCardM1.src
                                }), React.createElement("img", {
                                  className: "w-[280px]",
                                  src: rfqCardM2.src
                                }), React.createElement("img", {
                                  className: "w-[280px]",
                                  src: rfqCardM3.src
                                })))), React.createElement("section", {
                      className: "relative"
                    }, React.createElement("div", {
                          className: "container max-w-screen-lg mx-auto py-[60px]"
                        }, React.createElement("div", {
                              className: "bg-[#F6F9F6]  rounded-[40px] py-10 mx-5"
                            }, React.createElement("div", {
                                  className: "flex justify-center items-center flex-col"
                                }, React.createElement("div", {
                                      className: "text-[26px] font-bold"
                                    }, React.createElement("span", undefined, "업계 "), React.createElement("span", {
                                          className: "text-primary"
                                        }, "최저가로 "), React.createElement("span", undefined, "공급")), React.createElement("div", {
                                      className: "text-[17px] leading-6 tracking-tighter text-gray-700 mt-4 text-center whitespace-pre-line"
                                    }, "30곳 이상의 대형 공급업체의\n견적을 비교하여 기존 공급업체보다\n더 저렴한 가격을 보장해드립니다.")), React.createElement("div", {
                                  className: " mt-8 flex justify-center"
                                }, React.createElement("img", {
                                      className: "w-[280px]",
                                      src: rfqCardImgM1.src
                                    }))), React.createElement("div", {
                              className: "relative bg-[#F6F9F6] py-10 rounded-[40px] mt-5 mx-5"
                            }, React.createElement("div", {
                                  className: "flex justify-center items-center flex-col"
                                }, React.createElement("div", {
                                      className: "text-[26px] font-bold whitespace-pre-line"
                                    }, React.createElement("span", undefined, "재거래 시에도"), React.createElement("span", {
                                          className: "text-primary"
                                        }, "\n매번 최저가로")), React.createElement("div", {
                                      className: "text-[17px] leading-6 tracking-tighter text-gray-700 mt-4 whitespace-pre-line"
                                    }, "매 발주마다 최저가 견적만 자동 발송되어\n꾸준한 원가 절감효과를 누릴 수 있습니다."), React.createElement("div", {
                                      className: "flex justify-center items-center mt-10"
                                    }, React.createElement("img", {
                                          className: "w-[320px]",
                                          src: rfqCardImgM2.src
                                        })))))), React.createElement("section", {
                      className: "relative"
                    }, React.createElement("div", {
                          className: "py-[60px]"
                        }, React.createElement("div", {
                              className: "flex flex-col gap-[30px] px-5"
                            }, React.createElement("div", {
                                  className: "flex justify-center"
                                }, React.createElement("img", {
                                      className: "w-[410px]",
                                      src: rfqBox.src
                                    })), React.createElement("div", {
                                  className: "flex justify-center flex-col text-center"
                                }, React.createElement("div", {
                                      className: "text-[26px] font-bold"
                                    }, React.createElement("span", undefined, "한 박스도 "), React.createElement("span", {
                                          className: "text-primary"
                                        }, "무료배송")), React.createElement("div", {
                                      className: "text-[17px] leading-6 tracking-tighter text-gray-700 mt-4 whitespace-pre-line"
                                    }, "한 박스 이상 주문 시 매장 앞으로\n배송비 0원에 배송해드립니다."))))), React.createElement("section", {
                      className: "py-[110px] bg-[#3F4C65] "
                    }, React.createElement("div", {
                          className: "flex justify-center items-center flex-col text-white font-bold leading-9 text-[26px]"
                        }, React.createElement("h2", undefined, "첫 거래 시 "), React.createElement("h2", undefined, React.createElement("span", {
                                  className: "text-primary"
                                }, "10만원 추가할인!")), React.createElement("h2", undefined, "1분만에"), React.createElement("h2", undefined, "견적을 요청해보세요"), React.createElement("span", {
                              className: "text-[17px] font-normal leading-6 mt-5 whitespace-pre-wrap text-center"
                            }, "영업일 기준 견적요청 후\n2시간 내로 견적서가 도착!"), React.createElement("span", {
                              className: "text-[17px] font-normal leading-6 mt-2 whitespace-pre-wrap text-center text-gray-400"
                            }, "(단, 16시 이후 견적요청 건은\n다음 날 오전에 견적서를 발송해드려요)")), React.createElement("div", {
                          className: "flex justify-center mt-2.5"
                        }, React.createElement(RfqCreateRequestButton.make, {
                              className: buttonStyle,
                              position: "bottom"
                            })))), React.createElement(Footer_Buyer.MO.make, {}));
}

var MO = {
  make: Rfq_Buyer$MO
};

function $$default(props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Head, {
                  children: React.createElement("title", undefined, "신선하이 | 견적요청")
                }), props.deviceType >= 2 ? React.createElement(Rfq_Buyer$MO, {}) : React.createElement(Rfq_Buyer$PC, {}));
}

function getServerSideProps(ctx) {
  var environment = RelayEnv.environment({
        TAG: /* SinsunMarket */0,
        _0: Env.graphqlApiUrl
      });
  var gnbAndCategoryQuery = ServerSideHelper.gnbAndCategory(environment);
  var deviceType = DeviceDetect.detectDeviceFromCtx2(ctx.req);
  return ServerSideHelper.makeResultWithQuery(gnbAndCategoryQuery, environment, {
              deviceType: deviceType
            });
}

export {
  rfqBgImg ,
  rfqCard1 ,
  rfqCard2 ,
  rfqCard3 ,
  rfqBox ,
  rfqCardImg1 ,
  rfqCardImg2 ,
  rfqCardM1 ,
  rfqCardM2 ,
  rfqCardM3 ,
  rfqCardImgM1 ,
  rfqCardImgM2 ,
  rfqBgImgM ,
  PC ,
  MO ,
  $$default ,
  $$default as default,
  getServerSideProps ,
}
/* rfqBgImg Not a pure module */
