// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as IconSpinnerPlus from "../svgs/IconSpinnerPlus.mjs";
import * as IconSpinnerMinus from "../svgs/IconSpinnerMinus.mjs";

function setIntInRange(number, min, max) {
  if (Caml_obj.lessthan(number, min)) {
    return min;
  } else if (Caml_obj.greaterthan(number, max)) {
    return max;
  } else {
    return number;
  }
}

function Spinbox(props) {
  var onChange = props.onChange;
  var value = props.value;
  var max = props.max;
  var min = props.min;
  var max$1 = max !== undefined ? max : 999;
  var min$1 = min !== undefined ? min : 1;
  var onChangeValue = function (e) {
    var nonEmptyStr = e.target.value;
    var parsed = nonEmptyStr === "" ? min$1 : Belt_Option.map(Belt_Int.fromString(nonEmptyStr.replace(/[^0-9]/g, "")), (function (v$p) {
              return setIntInRange(v$p, min$1, max$1);
            }));
    Belt_Option.map(parsed, onChange);
  };
  return React.createElement("div", {
              className: "w-[7.5rem] h-10 flex border rounded-xl divide-x"
            }, React.createElement("button", {
                  className: "w-9 flex items-center justify-center",
                  disabled: value === min$1,
                  onClick: (function (param) {
                      Curry._1(onChange, value - 1 | 0);
                    })
                }, React.createElement(IconSpinnerMinus.make, {
                      fill: value === min$1 ? "#cccccc" : "#262626"
                    })), React.createElement("div", {
                  className: "flex flex-1 items-center justify-center"
                }, React.createElement("input", {
                      className: "w-[46px] text-center focus:outline-none",
                      value: String(value),
                      onChange: onChangeValue
                    })), React.createElement("button", {
                  className: "w-9 flex items-center justify-center",
                  disabled: value === max$1,
                  onClick: (function (param) {
                      Curry._1(onChange, value + 1 | 0);
                    })
                }, React.createElement(IconSpinnerPlus.make, {
                      fill: value === max$1 ? "#cccccc" : "#262626"
                    })));
}

var make = Spinbox;

export {
  setIntInRange ,
  make ,
}
/* react Not a pure module */
