// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayEnv from "./constants/RelayEnv.mjs";
import * as Js_promise from "rescript/lib/es6/js_promise.js";
import * as DeviceDetect from "./bindings/DeviceDetect.mjs";
import * as ShopMain_Buyer from "./pages/buyer/ShopMain_Buyer.mjs";
import * as GnbBannerList_Buyer from "./components/GnbBannerList_Buyer.mjs";
import * as ShopCategorySelect_Buyer from "./components/ShopCategorySelect_Buyer.mjs";
import * as ShopMain_SubBanner_Buyer from "./components/ShopMain_SubBanner_Buyer.mjs";
import * as ShopMain_MainBanner_Buyer from "./components/ShopMain_MainBanner_Buyer.mjs";
import * as ShopMain_CategoryList_Buyer from "./components/ShopMain_CategoryList_Buyer.mjs";

function $$default(props) {
  return React.createElement(ShopMain_Buyer.make, {
              deviceType: props.deviceType,
              gnbBanners: props.gnbBanners,
              mainBanners: props.mainBanners,
              subBanners: props.subBanners,
              categories: props.categories,
              displayCategories: props.displayCategories
            });
}

function getServerSideProps(ctx) {
  var deviceType = DeviceDetect.detectDeviceFromCtx2(ctx.req);
  return Js_promise.$$catch((function (err) {
                console.log("에러 GnbBannerListBuyerQuery", err);
                return Promise.resolve({
                            props: {
                              query: ctx.query,
                              deviceType: deviceType,
                              gnbBanners: [],
                              mainBanners: [],
                              subBanners: [],
                              categories: [],
                              displayCategories: []
                            }
                          });
              }), Js_promise.then_((function (res1) {
                    return Js_promise.then_((function (res2) {
                                  return Js_promise.then_((function (res3) {
                                                return Js_promise.then_((function (res4) {
                                                              return Js_promise.then_((function (res5) {
                                                                            return Promise.resolve({
                                                                                        props: {
                                                                                          query: ctx.query,
                                                                                          deviceType: deviceType,
                                                                                          gnbBanners: res1.gnbBanners,
                                                                                          mainBanners: res2.mainBanners,
                                                                                          subBanners: res3.subBanners,
                                                                                          categories: res4.mainDisplayCategories,
                                                                                          displayCategories: res5.displayCategories
                                                                                        }
                                                                                      });
                                                                          }), ShopCategorySelect_Buyer.Query.fetchPromised(RelayEnv.envSinsunMarket, {
                                                                              onlyDisplayable: true,
                                                                              parentId: undefined,
                                                                              types: ["NORMAL"]
                                                                            }, undefined, undefined, undefined));
                                                            }), ShopMain_CategoryList_Buyer.Query.fetchPromised(RelayEnv.envSinsunMarket, {
                                                                onlyDisplayable: true
                                                              }, undefined, undefined, undefined));
                                              }), ShopMain_SubBanner_Buyer.Query.fetchPromised(RelayEnv.envSinsunMarket, undefined, undefined, undefined, undefined));
                                }), ShopMain_MainBanner_Buyer.Query.fetchPromised(RelayEnv.envSinsunMarket, undefined, undefined, undefined, undefined));
                  }), GnbBannerList_Buyer.Query.fetchPromised(RelayEnv.envSinsunMarket, undefined, undefined, undefined, undefined)));
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
}
/* react Not a pure module */
